# Generated by Django 4.2.11 on 2024-05-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestudiantes', '0001_initial'),
    ]

    operations = [
    ]
