# Generated by Django 4.2.11 on 2024-05-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestudiantes', '0002_auto_20240511_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='estudiantes',
            field=models.ManyToManyField(related_name='cursos', to='maestudiantes.estudiante'),
        ),
    ]
